"""empty message

Revision ID: 2864afd3bdd7
Revises: b84027ddf051
Create Date: 2025-02-18 17:44:20.981464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2864afd3bdd7'
down_revision = 'b84027ddf051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
