"""empty message

Revision ID: a3fd498ec6fa
Revises: 2864afd3bdd7
Create Date: 2025-02-18 18:01:18.092448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fd498ec6fa'
down_revision = '2864afd3bdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_name_key', ['name'])

    # ### end Alembic commands ###
